module: bytes
module_version: 1.0
author: TBO Interactive GmbH & Co. KG
author_url: http://www.tbointeractive.com
copyright: '© 2016 [TBO Interactive GmbH & Co. KG](http://www.tbointeractive.com).'

# github_url: https://github.com/...
clean: true

#podspec: Bytes.podspec

#excluded_files: Example/

# swift_version: 3.0  # disabled due to https://github.com/realm/jazzy/issues/656

# in case we want to have our own structure
# custom_categories:
#   - name: iOS
#     children:
#         - ArrayTableViewDatasource

